### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by chawdamrunal** [devanshbatham/OpenRedireX#1]
(env) root@user-VirtualBox:/home/mru/OpenRedireX# python3.7 openredirex.py -l urls.txt -p payloads.txt --keyword FUZZ

             ____                   ____           ___          _  __
            / __ \____  ___  ____  / __ \___  ____/ (_)_______ | |/ /
           / / / / __ \/ _ \/ __ \/ /_/ / _ \/ __  / / ___/ _ \|   / 
          / /_/ / /_/ /  __/ / / / _, _/  __/ /_/ / / /  /  __/   |  
          \____/ .___/\___/_/ /_/_/ |_|\___/\__,_/_/_/   \___/_/|_|  
                /_/                                                    

                          - By Devansh(Asm0d3us) and NullPxl

    
Traceback (most recent call last):
  File "openredirex.py", line 125, in <module>
    main()
  File "openredirex.py", line 107, in main
    asyncio.run(redirme(args.list, args.payloads, args.keyword))
AttributeError: module 'asyncio' has no attribute 'run'

**Comment by devanshbatham** [comment]
use python 3.7.5 or higher !
