### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by 0x0asif** [devanshbatham/OpenRedireX#11]
ultimate@Ultimate-Haxor:~/Desktop/Quick_Recon/OpenRedireX$ python3.7 openredirex.py -l urls.txt -p payloads.txt --keyword FUZZ
Traceback (most recent call last):
  File "openredirex.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
ultimate@Ultimate-Haxor:~/Desktop/Quick_Recon/OpenRedireX$ 

all pip installed. But it not work properly.

**Comment by litt1eb0yy** [comment]
install aiohttp using the below command :)
```
pip3 install aiohttp
```

**Comment by rakshitks** [comment]
Try this once
Please follow these steps to resolve the error

Install python3.7
`sudo apt install python3.7-minimal`

Install python3.7 dev
`sudo apt-get install python3.7-dev`

Use this command while running
testphp.vulnweb.com text file contains something like this
`http://testphp.vulnweb.com:80/secured/phpinfo.php?=FUZZ`

**Then use this command**
`python3.7 openredirex.py -l testphp.vulnweb.com.txt -p payloads.txt --keyword=FUZZ`

**Comment by devanshbatham** [comment]
Closing this issue as I have updated the entire script. File a new issue if you face any problems running it
