### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by simrotion13** [devanshbatham/OpenRedireX#13]
root@bbmachine:~/tools/OpenRedireX# python3 openredirex.py -h
Traceback (most recent call last):
  File "openredirex.py", line 3, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by Rahimianes** [comment]
Hello 
you can install this package with the below command:
pip3 install aiohttp

**Comment by rakshitks** [comment]
@simrotion13 try this
https://github.com/devanshbatham/OpenRedireX/issues/14

**Comment by devanshbatham** [comment]
Closing this issue as I have updated the entire script. File a new issue if you face any problems running it
