### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute 'run'

### ISSUE THREAD

**Issue by conorxx1** [devanshbatham/OpenRedireX#14]
Traceback (most recent call last):
  File "openredirex.py", line 126, in <module>
    main()
  File "openredirex.py", line 106, in main
    asyncio.run(redirme(url_list , args.payloads, args.keyword))
AttributeError: module 'asyncio' has no attribute 'run'

**Comment by rakshitks** [comment]
Please follow these steps to resolve the error 
1. Install python3.7 
`sudo apt install python3.7-minimal`

2. Install python3.7 dev
`sudo apt-get install python3.7-dev`

It will start working :)
**Tested on ubuntu 18**

**Comment by devanshbatham** [comment]
Closing this issue as I have updated the entire script. File a new issue if you face any problems running it
