### ISSUE TITLE
zsh: killed 

### ISSUE THREAD

**Issue by sasholy** [devanshbatham/OpenRedireX#17]
1. python3 openredirex.py -l /home/kali/Desktop/redir.txt -p /home/kali/Desktop/redirlist.txt --keyword=FUZZ 

2.    
[+] Total URLs loaded : 64231
[+] Total Payloads loaded : 866                                                    
[+] Scanning Started [Only Suspected URLs with redirect history will be displayed , all others will be ignored]                                                       

**zsh: killed     python3 openredirex.py -l /home/kali/Desktop/redir.txt -p  --keyword=FUZZ**

kali linux

**Comment by devanshbatham** [comment]
Closing this issue as I have updated the entire script. File a new issue if you face any problems running it
