### ISSUE TITLE
AIOHTTP

### ISSUE THREAD

**Issue by kmalik31** [devanshbatham/OpenRedireX#2]
root@localhost:~/Tools/OpenRedireX# python3.7 openredirex.py -l url.txt -p payloads.txt --keyword FUZZ
Traceback (most recent call last):
  File "openredirex.py", line 2, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by kmalik31** [comment]
[+] Total URLs loaded : 1701
[+] Total Payloads loaded : 44
[+] Scanning Started [Only Suspected URLs with redirect history will be displayed , all others will be ignored]

**Comment by kmalik31** [comment]
I've Installed it using pip3 install aiohttp

**Comment by devanshbatham** [comment]
Follow readme , and try to use this inside a virtual environment !

**Comment by tpirneci** [comment]
python3.7 -m pip install aiohttp
