### ISSUE TITLE
error while processing the url

### ISSUE THREAD

**Issue by oldDuDe124** [devanshbatham/OpenRedireX#21]
hi 

i'm facing this issue here:

echo 'https://domain.tld&path=FUZZ' | openredirex -k FUZZ

   ____                   ____           ___               
  / __ \____  ___  ____  / __ \___  ____/ (_)_______  _  __
 / / / / __ \/ _ \/ __ \/ /_/ / _ \/ __  / / ___/ _ \| |/_/
/ /_/ / /_/ /  __/ / / / _, _/  __/ /_/ / / /  /  __/>  <  
\____/ .___/\___/_/ /_/_/ |_|\___/\__,_/_/_/   \___/_/|_|  
    /_/                                                    

    
[INFO] Processing 1 URLs with 3 payloads.
[ERROR] Error fetching: https://domain.tld&path=//example.com@google.com/%2f..
[ERROR] Error fetching: https://domain.tld&path=///google.com/%2f..
[ERROR] Error fetching: https://domain.tld&path=///example.com@google.com/%2f..
Processing: 100%|████████████████████| 3/3 [00:02<00:00, 14.72url/s]

i know domain.tld has an open redirect vulnerability in the given parameter but this tool doesn't seem to be finding that and i don't know what is causing the error either.
i'm using ubuntu 22 and i have installed all the required python libraries.

i'll appreicate your help

**Comment by devanshbatham** [comment]
Currently it only detects redirects based on the Location header, so it it is a JS based redirect, it will not be detected.
