### ISSUE TITLE
ModuleNotFoundError: No module named 'aiohttp'

### ISSUE THREAD

**Issue by ifediri** [devanshbatham/OpenRedireX#3]
(env) root@kali:~/OpenRedireX# python3.7 openredirex.py -u "https://REDACTED_TARGET=FUZZ" -p payloads.txt --keyword FUZZ
Traceback (most recent call last):
  File "openredirex.py", line 2, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'

**Comment by ifediri** [comment]
**I did install and import aiohttp**

(env) root@kali:~# pip3 install aiohttp
Requirement already satisfied: aiohttp in ./OpenRedireX/env/lib/python3.8/site-packages (3.6.2)
Requirement already satisfied: yarl<2.0,>=1.0 in ./OpenRedireX/env/lib/python3.8/site-packages (from aiohttp) (1.4.2)
Requirement already satisfied: multidict<5.0,>=4.5 in ./OpenRedireX/env/lib/python3.8/site-packages (from aiohttp) (4.7.5)
Requirement already satisfied: chardet<4.0,>=2.0 in ./OpenRedireX/env/lib/python3.8/site-packages (from aiohttp) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in ./OpenRedireX/env/lib/python3.8/site-packages (from aiohttp) (19.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in ./OpenRedireX/env/lib/python3.8/site-packages (from aiohttp) (3.0.1)
Requirement already satisfied: idna>=2.0 in ./OpenRedireX/env/lib/python3.8/site-packages (from yarl<2.0,>=1.0->aiohttp) (2.9)

**but issue and error continued** when I run the tool OpenRedirecX

**Comment by NullPxl** [comment]
If you look in the pip3 message, it says:
 "Requirement already satisfied: aiohttp in ./OpenRedireX/env/lib/**python3.8**/site-packages"
Meaning your pip3 refers to python3.8, and you are running openredirex.py with `python3.7`.
You will need to install aiohttp for whichever Python version you want to run the script with.
